import Vue from 'vue';

import Caps from './Caps.vue';
import Lc from './Lc.vue';
import Uc from './Uc.vue';
import Green from './Green.vue';
import Gold from './Gold.vue';
import Red from './Red.vue';
import Badge from './Badge.vue';
import ProgressBar from './ProgressBar.vue';
import Btn from './Btn.vue';
import Ask from './Ask.vue';
import Ok from './Ok.vue';
import Confirm from './Confirm.vue';
import Opt from './Opt.vue';
import Menu from './Menu.vue';
import Info from './Info.vue';
import Section from './Section.vue';
import Modal from './Modal.vue';

Vue.component('caps', Caps);
Vue.component('lc', Lc);
Vue.component('uc', Uc);
Vue.component('green', Green);
Vue.component('gold', Gold);
Vue.component('red', Red);
Vue.component('badge', Badge);
Vue.component('progress-bar', ProgressBar);
Vue.component('btn', Btn);
Vue.component('ask', Ask);
Vue.component('ok', Ok);
Vue.component('confirm', Confirm);
Vue.component('Opt', Opt);
Vue.component('Menu', Menu);
Vue.component('Info', Info);
Vue.component('Section', Section);
Vue.component('modal', Modal);
