export default [
  {
    name:    "Food production",
    avail:   ["mineral rich", "rocky", "subterranean"],
    rewards: ["food"],
    pay:     3,
    desc:    `
      Whether harvesting produce in an open field on Earth, tending an
      acrid fungal orchard orbiting Enceladus, or producing prepackaged,
      processed foods in a factory on Ceres, the task of producing of enough
      food to feed the entire human population is always in need of day
      laborers.
    `,
  },
  {
    name:    "Mine ore",
    avail:   ["mineral rich", "rocky", "subterranean"],
    rewards: ["ore", "minerals"],
    pay:     4,
    desc:    `
      Automated heavy excavating equipment deep underground carries tonnes
      of material to the surface. The arduous task of breaking and sorting
      the product is left to humans.
    `,
  },
  {
    name:    "Harvest water ice",
    avail:   ["icy", "water rich"],
    rewards: ["water", "minerals"],
    pay:     6,
    desc:    `
      Water ice is available on the surface of many moons and planets
      throughout the system. It is occassionally found alongside valuable or
      useful mineral deposits. It is a back-breaking job that, by definition,
      is performed in freezing temperatures. Although automation helps some,
      the heat generated by excavators makes the product more difficult to
      contain and transport. The result is regular demand for able-bodied
      workers to break and process ice.
    `,
  },
  {
    name:    "Asteroid mining",
    avail:   ["asteroids"],
    rewards: ["ore", "minerals"],
    pay:     8,
    desc:    `
      Called the "Tiara of Ceres" (at least by the marketing departments of
      the various mining interests stationed there), the asteroid belt
      provides exquisitely easy access to enough raw material to supply all
      of human industry for millenia. Automated excavators tunnel down into
      the rock, fracturing large fragments in the hunt for a vein of
      something profitable. Smaller, human-piloted mechs can then process
      the floating fragment and haul the raw material back to the ship.
    `,
  },
  {
    name:    "Harvest ring ice",
    avail:   ["ringed system"],
    rewards: ["water", "hydrocarbons", "minerals"],
    pay:     10,
    desc:    `
      Water ice is available in plenty for the taking around the gas giants.
      While dangerous to harvest, water is the most commonly traded resource
      in the Solar System and is always in high demmand. The ring systems
      are also a valuable source of the hydrocarbons required to create
      fertile soil.
    `,
  },
];
